{% set name = "pan3d" %}
{% set version = "0.14.1" %}

{% set vtk_version = "9.4.1" %}

# Based on platform, vtk 9.4.1 required different minimum python
{% if linux %}
  {% set python_min = "3.13" %}
{% elif osx %}
  {% set python_min = "3.12" %}
{% else %}
  {% set python_min = "3.9" %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pan3d-{{ version }}.tar.gz
  sha256: 0d7d4891e0a359e9fa84a141a8d88df490b9057b574555f9992e7c96ebe341e0

build:
  entry_points:
    - xr-viewer = pan3d.viewers.preview:main
    - xr-catalog = pan3d.viewers.catalog:main
    - xr-slicer = pan3d.explorers.slicer:main
    - xr-globe = pan3d.explorers.globe:main
    - xr-contour = pan3d.explorers.contour:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - vtk >={{ vtk_version }}
    - requests >=2.31
    - aiohttp
    - xarray >=2023.8
    # viewers/explorers
    - trame >=3.6
    - trame-vtk >=2.6
    # Removing the local rendering support for now as it requires special vtk build
    # trame-vtklocal
    - trame-vuetify >=2.4
    # esgf
    - intake-esgf >=2024.1
    # pangeo
    - intake >=2.0  # latest has plugin errors
    - intake-xarray >=2.0
    - intake-esm >=2023.11
    - s3fs >=2024.2
    - gcsfs >=2024.2
    # xcdat
    - xcdat

test:
  imports:
    - pan3d
  commands:
    - pip check
    - xr-viewer --help
    - xr-catalog --help
    - xr-slicer --help
    - xr-globe --help
    - xr-contour --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/Kitware/pan3d
  summary: Utility package for processing and visualizing 3D datasets
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ayenpure
    - jourdain